Repository alpenlabs/strata-bridge, pull requests merged in 2025-05, with the labels that each got.

#133 chore(tls) don't convert to der
  .gitignore
  docker/gen_s2_tls.sh
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
  docker/vol/secret-service-1/config.toml
  docker/vol/secret-service-2/config.toml
  docker/vol/secret-service-3/config.toml
  scripts/ca-and-tls.sh
Labels: P0 - Blocks Development, required

#135 STR-1316: Inconsistent Burial Semantics
  crates/btc-notify/src/client.rs
  crates/btc-notify/src/event.rs
  crates/btc-notify/src/state_machine.rs
  crates/duty-tracker/src/contract_manager.rs
Labels: bugfix, P1 - Blocks Release

#134 STR-1309: Implement the RPC server V2
  Cargo.lock
  bin/alpen-bridge/Cargo.toml
  bin/alpen-bridge/src/rpc_server.rs
  crates/db/src/inmemory/tracker.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_persister.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/primitives/src/duties.rs
  crates/rpc/src/traits.rs
  crates/rpc/src/types.rs
  migrations/20241113060253_init_schema.sql
Labels: enhancement, P1 - Blocks Release

#136 fix: dns lookup for secret service server address
  bin/alpen-bridge/src/mode/operator.rs
Labels: enhancement, P2 - Nice to Have

#138 Only RPC sync to the buried height
  bin/alpen-bridge/src/config.rs
  crates/btc-notify/src/client.rs
  crates/duty-tracker/src/contract_manager.rs
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
Labels: bugfix, P1 - Blocks Release

#141 give zmq state machine unburied block queue on startup to prevent not…
  bin/alpen-bridge/src/mode/operator.rs
  crates/btc-notify/src/client.rs
  crates/btc-notify/src/config.rs
  crates/btc-notify/src/state_machine.rs
  crates/duty-tracker/src/contract_manager.rs
Labels: bugfix, P0 - Blocks Development

#131 MICRO: Chore/debug assert warnings
  crates/duty-tracker/src/contract_state_machine.rs
  crates/tx-graph/src/peg_out_graph.rs
  crates/tx-graph/src/pog_musig_functor.rs
Labels: enhancement, P2 - Nice to Have

#142 STR-1344: rpc state cache does not get updated
  bin/alpen-bridge/Cargo.toml
  bin/alpen-bridge/src/config.rs
  bin/alpen-bridge/src/constants.rs
  bin/alpen-bridge/src/mode/operator.rs
  bin/alpen-bridge/src/rpc_server.rs
  crates/duty-tracker/src/contract_persister.rs
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
  migrations/20241113060253_init_schema.sql
Labels: bugfix, P0 - Blocks Development

#143 STR-1343 commit aggregated sig to state and serve via rpc
  Cargo.lock
  bin/alpen-bridge/src/rpc_server.rs
  crates/agent/Cargo.toml
  crates/agent/src/operator.rs
  crates/db/src/persistent/sqlite.rs
  crates/duty-tracker/Cargo.toml
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/errors.rs
  crates/duty-tracker/src/executors/deposit.rs
  crates/duty-tracker/src/executors/optimistic_withdrawal.rs
  crates/duty-tracker/src/stake_chain_persister.rs
  crates/duty-tracker/src/stake_chain_state_machine.rs
  crates/duty-tracker/src/tx_driver.rs
  crates/rpc/src/traits.rs
  crates/stake-chain/Cargo.toml
  crates/stake-chain/src/stake_chain.rs
  crates/stake-chain/src/transactions/stake.rs
  crates/tx-graph/src/peg_out_graph.rs
  crates/tx-graph/src/transactions/covenant_tx.rs
Labels: enhancement, P0 - Blocks Development, required

#149 TxDriver idempotence
  Cargo.lock
  Cargo.toml
  crates/algebra/Cargo.toml
  crates/algebra/src/lib.rs
  crates/algebra/src/monoid.rs
  crates/algebra/src/semigroup.rs
  crates/btc-notify/Cargo.toml
  crates/btc-notify/src/client.rs
  crates/btc-notify/src/lib.rs
  crates/btc-notify/src/state_machine.rs
  crates/duty-tracker/Cargo.toml
  crates/duty-tracker/src/tx_driver.rs
  crates/test-utils/Cargo.toml
  crates/test-utils/src/bitcoin.rs
  crates/test-utils/src/lib.rs
Labels: bugfix, P1 - Blocks Release
