Repository alpenlabs/strata-bridge, pull requests merged in 2025-06, with the labels that each got.

#154 STR-1429: Restrict magic bytes in bridge to 4 bytes
  Cargo.lock
  bin/alpen-bridge/src/mode/operator.rs
  bin/alpen-bridge/src/params.rs
  bin/alpen-bridge/src/rpc_server.rs
  bin/dev-cli/Cargo.toml
  bin/dev-cli/src/bridge_in/deposit_request.rs
  bin/dev-cli/src/constants.rs
  bridge-guest-builder/bridge-guest/Cargo.lock
  crates/agent/src/operator.rs
  crates/bridge-proof/protocol/src/statement.rs
  crates/bridge-proof/protocol/src/tx_info.rs
  crates/bridge-proof/test-utils/src/lib.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_persister.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/predicates.rs
  crates/params/Cargo.toml
  crates/params/src/default.rs
  crates/params/src/errors.rs
  crates/params/src/lib.rs
  crates/params/src/tx_graph.rs
  crates/params/src/types.rs
  crates/primitives/src/deposit.rs
  crates/primitives/src/scripts/general.rs
  crates/primitives/src/scripts/metadata.rs
  crates/tx-graph/src/transactions/deposit.rs
  crates/tx-graph/src/transactions/withdrawal_fulfillment.rs
  docker/vol/alpen-bridge-1/params.toml
  docker/vol/alpen-bridge-2/params.toml
  docker/vol/alpen-bridge-3/params.toml
  test-data/blocks.bin
  test-data/chainstate.borsh
  test-data/op_signature.bin
  test-data/rollup_params.json
Labels: bugfix, P1 - Blocks Release

#150 STR-1318: Service `PubNonce`s, `AggNonce`s and `PartialSignature`s
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/executors/deposit.rs
Labels: bugfix, P1 - Blocks Release

#179 docker: remove `memory_profiling` build
  docker/alpen-bridge/Dockerfile
  docker/secret-service/Dockerfile
Labels: P1 - Blocks Release

#184 Fix/unknown session after restart
  compose.yml
  crates/db/src/inmemory/public.rs
  crates/db/src/persistent/models.rs
  crates/db/src/persistent/sqlite.rs
  crates/db/src/persistent/types.rs
  crates/db/src/public.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_persister.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/executors/deposit.rs
  crates/duty-tracker/src/stake_chain_persister.rs
  crates/duty-tracker/src/stake_chain_state_machine.rs
  crates/stake-chain/src/stake_chain.rs
  crates/stake-chain/src/transactions/stake.rs
  crates/tx-graph/src/peg_out_graph.rs
  docker/bitcoin/entrypoint.sh
  migrations/20241113060253_init_schema.sql
Labels: bugfix, enhancement, P1 - Blocks Release, required

#183 Feat/update bitvm wots api and rust
  Cargo.lock
  Cargo.toml
  Makefile
  bin/alpen-bridge/src/main.rs
  bin/alpen-bridge/src/params.rs
  bin/assert-splitter/Cargo.toml
  bin/assert-splitter/src/lib.rs
  bin/assert-splitter/src/main.rs
  bin/dev-cli/src/handlers/bridge_in.rs
  bin/dev-cli/src/handlers/disprove.rs
  bin/secret-service/src/seeded_impl/wots.rs
  crates/btc-notify/src/state_machine.rs
  crates/connectors/Cargo.toml
  crates/connectors/src/connector_a3.rs
  crates/connectors/src/connector_c0.rs
  crates/connectors/src/connector_k.rs
  crates/connectors/src/connector_p.rs
  crates/connectors/src/connector_s.rs
  crates/connectors/src/connectors_a.rs
  crates/connectors/src/partial_verification_scripts.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/executors/contested_withdrawal.rs
  crates/p2p-service/src/tests/gossipsub.rs
  crates/primitives/src/scripts/commitments.rs
  crates/primitives/src/scripts/general.rs
  crates/primitives/src/scripts/parse_witness.rs
  crates/primitives/src/scripts/transform.rs
  crates/primitives/src/wots.rs
  crates/secret-service-client/src/wots.rs
  crates/secret-service-proto/src/v1/traits.rs
  crates/secret-service-proto/src/v1/wire.rs
  crates/stake-chain/src/errors.rs
  crates/test-utils/src/lib.rs
  crates/test-utils/src/wots.rs
  crates/tx-graph/src/peg_out_graph.rs
  crates/tx-graph/src/transactions/assert_data.rs
  crates/tx-graph/src/transactions/burn_payouts.rs
  crates/tx-graph/src/transactions/claim.rs
  crates/tx-graph/src/transactions/cpfp.rs
  crates/tx-graph/src/transactions/disprove.rs
  crates/tx-graph/src/transactions/errors.rs
  crates/tx-graph/src/transactions/payout.rs
  crates/tx-graph/src/transactions/payout_optimistic.rs
  crates/tx-graph/src/transactions/post_assert.rs
  crates/tx-graph/src/transactions/pre_assert.rs
  crates/tx-graph/src/transactions/withdrawal_fulfillment.rs
  crates/wots/src/lib.rs
  docker/vol/alpen-bridge-1/strata-bridge.vk
  docker/vol/alpen-bridge-2/strata-bridge.sp1vk
  docker/vol/alpen-bridge-2/strata-bridge.vk
  docker/vol/alpen-bridge-3/strata-bridge.vk
  rust-toolchain.toml
  strata_bridge_groth16_vk.hex
Labels: enhancement, P1 - Blocks Release, dependencies

#186 log: fix duplicate StakeChainPersister logs
  crates/duty-tracker/src/stake_chain_persister.rs
Labels: P2 - Nice to Have

#189 Fix/Do not regenerate graphs when nagged
  crates/duty-tracker/src/contract_actor.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_state_machine.rs
Labels: P2 - Nice to Have, perf ⚡️

#187 STR-1529: Completed contracts should also account for Disproven contracts
  crates/duty-tracker/src/contract_actor.rs
Labels: P1 - Blocks Release

#193 Fix/update contract indexing to handle actor shutdown
  crates/duty-tracker/src/contract_actor.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/stake_chain_state_machine.rs
Labels: bugfix, P1 - Blocks Release, required
