Repository alpenlabs/strata-bridge, pull requests merged in 2025-07, with the labels that each got.

#185 Allow multiple deposits requests per block
  Cargo.lock
  bin/alpen-bridge/src/config.rs
  bin/alpen-bridge/src/main.rs
  bin/alpen-bridge/src/mode/operator.rs
  bin/alpen-bridge/src/rpc_server.rs
  compose.yml
  crates/algebra/src/category.rs
  crates/algebra/src/curry.rs
  crates/algebra/src/lib.rs
  crates/algebra/src/predicate.rs
  crates/common/src/logging.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/contract_state_machine.rs
  crates/duty-tracker/src/errors.rs
  crates/duty-tracker/src/executors/contested_withdrawal.rs
  crates/duty-tracker/src/executors/deposit.rs
  crates/duty-tracker/src/executors/optimistic_withdrawal.rs
  crates/duty-tracker/src/executors/proof_handler.rs
  crates/duty-tracker/src/stake_chain_persister.rs
  crates/duty-tracker/src/stake_chain_state_machine.rs
  crates/duty-tracker/src/tx_driver.rs
  crates/operator-wallet/Cargo.toml
  crates/operator-wallet/src/lib.rs
  crates/operator-wallet/src/sync.rs
  crates/p2p-service/src/bootstrap.rs
  crates/p2p-service/src/message_handler.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/operator_table.rs
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
Labels: P1 - Blocks Release

#197 fix/publish partials for all graphs concurrently
  crates/duty-tracker/src/contract_state_machine.rs
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
Labels: bugfix, P1 - Blocks Release, perf ⚡️

#196 revert: Actor-based parallelism
  crates/duty-tracker/src/contract_manager.rs
Labels: P1 - Blocks Release

#209 feat!: add claim and withdraw data to `ContractState`s past `Assigned`
  bin/alpen-bridge/src/rpc_server.rs
  crates/duty-tracker/src/contract_state_machine.rs
Labels: P1 - Blocks Release

#214 docs(bridge-proof): clarify the intent behind the current value of header length
  crates/bridge-proof/protocol/src/statement.rs
Labels: documentation, P2 - Nice to Have

#213 fix(rpc): only return active graph's claim txids.
  bin/alpen-bridge/src/rpc_server.rs
Labels: P1 - Blocks Release

#212 feat: graceful shutdown
  Cargo.lock
  Cargo.toml
  bin/alpen-bridge/Cargo.toml
  bin/alpen-bridge/src/config.rs
  bin/alpen-bridge/src/main.rs
  bin/alpen-bridge/src/mode/operator.rs
  bin/alpen-bridge/src/mode/verifier.rs
  crates/duty-tracker/Cargo.toml
  crates/duty-tracker/src/contract_manager.rs
  crates/duty-tracker/src/errors.rs
  crates/duty-tracker/src/lib.rs
  crates/duty-tracker/src/shutdown.rs
Labels: P2 - Nice to Have

#215 STR-1561 execute withdrawal fulfillments in parallel
  .gitignore
  .justfile
  bin/alpen-bridge/src/main.rs
  bin/mock-checkpoint/README.md
  crates/duty-tracker/src/executors/deposit.rs
  crates/duty-tracker/src/executors/optimistic_withdrawal.rs
  crates/operator-wallet/src/lib.rs
  docker/bitcoin/entrypoint.sh
  docker/vol/alpen-bridge-1/config.toml
  docker/vol/alpen-bridge-2/config.toml
  docker/vol/alpen-bridge-3/config.toml
Labels: bugfix, P1 - Blocks Release, required

#216 fix(tx-graph): use `TapSighashType::All` in deposit to maintain compatibility
  crates/algebra/Cargo.toml
  crates/tx-graph/src/transactions/deposit.rs
Labels: bugfix, P1 - Blocks Release, required

#217 fix: change all taproot sighashes to `Default` and better parsing
  crates/duty-tracker/src/executors/deposit.rs
  crates/tx-graph/src/transactions/deposit.rs
Labels: P1 - Blocks Release

#222 duty-tracker: actually persist deposit setup duties on time
  crates/duty-tracker/src/contract_manager.rs
Labels: bugfix, P1 - Blocks Release

#224 Bugfix/unbounded ouroboros
  bin/alpen-bridge/src/mode/operator.rs
  crates/duty-tracker/src/contract_manager.rs
  crates/p2p-service/src/message_handler.rs
Labels: bugfix, P1 - Blocks Release

#234 fix(duty-tracker): actually nag for root partials
  crates/duty-tracker/src/contract_manager.rs
Labels: bugfix, P1 - Blocks Release, required

#241 fix(bridge-proof): typo in tests
  crates/bridge-proof/primitives/src/tx.rs
Labels: P2 - Nice to Have

#239 fix!(alpen-bridge): missing RPC claim information for `Resolved` contracts
  bin/alpen-bridge/src/rpc_server.rs
  crates/rpc/src/types.rs
Labels: P1 - Blocks Release, needs backport ⚠️
